### ISSUE TITLE
Block part messages on chanserv/quiet

### ISSUE THREAD

**Issue by B00mX0r** [shalture/shalture#45] opened 2015-02-02 05:17 UTC
Parting and rejoining a channel can be used to bypass /cs quiet. Inspired has an extban "p" that blocks part messages from a user.

**Comment by GLolol** [comment] 2015-02-02 05:26
Blocking part messages is something done on the IRCd side, not something services can enforce. This is most likely a feature request for your IRCd and not shalture.

**Comment by B00mX0r** [comment] 2015-02-02 06:12
Sorry if I wasn't clear. I meant that on inspired, for /cs quiet, it sets extban p just like it sets extban m. 
/mode #chan +b p:mask -- Don't show part messages
/mode #chan +b m:mask -- Mute user

**Comment by kaniini** [comment] 2015-02-02 06:15
This is something InspIRCd should fix.  Working around InspIRCd bugs in services seems like a losing proposition.

**Comment by GLolol** [comment] 2015-02-02 06:21
If extban `m:` were to implicitly have the affect of `p:`, then I think the latter extban would be useless. Seeing that both are independent modules, I doubt what you're trying to achieve is practical.

Why not set the `+b p:mask` ban yourself?

**Comment by kaniini** [comment] 2015-02-02 06:22
The latter extban is already worthless, and the fact that they are independent modules is a misdesign.  This is not a bug in services at any rate.

**Comment by B00mX0r** [comment] 2015-02-02 06:52
It's not a bug in InspIRCd nor Shalture. I agree that it's a misdesign, though.

**Comment by Mikaela** [comment] 2015-02-02 08:34
https://github.com/inspircd/inspircd/issues/979

**Comment by nyuszika7h** [comment] 2015-11-18 20:35
@ilbelkyr not a services issue, you can close this.

**Closed** 2015-11-22 11:41 UTC
